components:
  schemas:
    ErrorMessage:
      properties:
        message:
          type: string
      type: object
    MakeTranslationPayload:
      properties:
        source_locale:
          type: string
        target_locale:
          type: string
        text:
          type: string
      required:
      - source_locale
      - target_locale
      - text
      type: object
    MakeTranslationResponse:
      properties:
        translated_text:
          type: string
      type: object
    PingResponse:
      properties:
        message:
          type: string
      type: object
    SupportedLocaleResponse:
      properties:
        name:
          type: string
        tag:
          type: string
      type: object
info:
  contact: {}
  description: API for pocket slate
  license:
    name: MIT
    url: https://github.com/kamaal111/pocket-slate-api/blob/main/LICENSE
  title: Pocket slate API
  version: '1.0'
openapi: 3.0.3
paths:
  /health/ping:
    get:
      description: Pings the server
      operationId: healthPing
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
          description: OK
      summary: Checks if server is up or down
      tags:
      - health
  /translations:
    post:
      description: Translates the given text in the payload from source locale to
        target locale.
      operationId: makeTranslation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MakeTranslationResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Forbidden
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Unprocessable Entity
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Internal Server Error
      summary: Translate text.
      tags:
      - translations
  /translations/supported-locales:
    get:
      description: Gets all the supported locales that can be used to translate.
      operationId: getSupportedLocales
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportedLocaleResponse'
                type: array
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Bad Request
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Forbidden
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Unprocessable Entity
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          description: Internal Server Error
      summary: Gets supported locales.
      tags:
      - translations
