components:
  schemas:
    ErrorMessage:
      properties:
        message:
          type: string
      type: object
    MakeTranslationPayload:
      properties:
        source_locale:
          type: string
        target_locale:
          type: string
        text:
          type: string
      required:
        - source_locale
        - target_locale
        - text
      type: object
    MakeTranslationResponse:
      properties:
        translated_text:
          type: string
      type: object
    PingResponse:
      properties:
        message:
          type: string
      type: object
    SupportedLocaleResponse:
      properties:
        name:
          type: string
        tag:
          type: string
      type: object
    SupportedLocaleResponses:
      schema:
        $ref: "#/components/schemas/SupportedLocaleResponse"
        type: array
info:
  contact: {}
  description: API for pocket slate
  license:
    name: MIT
    url: https://github.com/kamaal111/pocket-slate-api/blob/main/LICENSE
  title: Pocket slate API
  version: "1.0"
openapi: 3.0.3
paths:
  /health/ping:
    get:
      description: Pings the server
      operationId: healthPing
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PingResponse"
          description: OK
      summary: Checks if server is up or down
      tags:
        - health
  /translations:
    post:
      description:
        Translates the given text in the payload from source locale to
        target locale.
      operationId: makeTranslation
      parameters:
        - description: The version of the app.
          example: 4.2.0
          in: header
          name: App-Version
          required: true
          schema:
            type: string
        - description: The name of the app.
          example: sup-app
          in: header
          name: App-Name
          required: true
          schema:
            type: string
        - description: API key registered to the app.
          example: 1234lmao
          in: header
          name: Api-Key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MakeTranslationPayload"
        description: The text to translate.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MakeTranslationResponse"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Bad Request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Forbidden
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Internal Server Error
      summary: Translate text.
      tags:
        - translations
  /translations/supported-locales:
    get:
      description: Gets all the supported locales that can be used to translate.
      operationId: getSupportedLocales
      parameters:
        - description: The target language to translate the locales to.
          example: it
          in: query
          name: target
          schema:
            type: string
        - description: The version of the app.
          example: 4.2.0
          in: header
          name: App-Version
          required: true
          schema:
            type: string
        - description: The name of the app.
          example: sup-app
          in: header
          name: App-Name
          required: true
          schema:
            type: string
        - description: API key registered to the app.
          example: 1234lmao
          in: header
          name: Api-Key
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SupportedLocaleResponses"
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Bad Request
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Forbidden
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Unprocessable Entity
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
          description: Internal Server Error
      summary: Gets supported locales.
      tags:
        - translations
