name: CI

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  XCODE_APP_NAME: Xcode_14.3.app

jobs:
  quality:
    name: Quality
    timeout-minutes: 5
    runs-on: macos-13
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Swift lint
        run: just lint

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Check diff
        run: just assert-has-no-diffs

  test:
    name: Test
    timeout-minutes: 15
    runs-on: macos-13
    needs: [quality]
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Trust Swift plugins
        run: just trust-swift-plugins

      - name: Test
        env:
          DESTINATION: "platform=iOS Simulator,name=iPhone 14 Pro Max"
        run: just test

      - name: Check diff
        run: just assert-has-no-diffs

  build:
    name: Build
    timeout-minutes: 15
    runs-on: macos-13
    needs: [quality]
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Install node modules
        run: just install-node-modules

      - name: Format
        run: just format

      - name: Trust Swift plugins
        run: just trust-swift-plugins

      - name: Build
        env:
          DESTINATION: "platform=iOS Simulator,name=iPhone 14 Pro Max"
        run: just build

      - name: Check diff
        run: just assert-has-no-diffs

  deployIOS:
    name: Deploy iOS
    timeout-minutes: 15
    runs-on: macos-13
    needs: [quality, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Select Xcode version
        run: |
          ls -d /Applications/Xcode*
          sudo xcode-select --switch /Applications/$XCODE_APP_NAME/Contents/Developer

      - name: Trust Swift plugins
        run: just trust-swift-plugins

      - name: Setup - Ruby and bundler dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      # - name: Import signing certificate
      #   env:
      #     SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
      #     SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}
      #     KEYCHAIN_PASSPHRASE: ${{ secrets.KEYCHAIN_PASSPHRASE }}
      #   run: bash Scripts/import_signing_certificate.bash

      - name: Bump build number
        run: |
          echo "Setting build number to ${{ github.run_number }}"
          just bump-version ${{ github.run_number }}

      - name: Archive app
        run: just archive
